---
- name: Converge
  hosts: all
  gather_facts: false
  tasks:
    - name: "Include utils"
      ansible.builtin.include_role:
        name: "utils"


- name: create temporary directory
  tempfile:
    state: directory
    suffix: .test
  register: remote_tmp_dir
#  notify:
#    - delete temporary directory

- name: record temporary directory
  set_fact:
    remote_tmp_dir: "{{ remote_tmp_dir.path }}"


- name: Converge
  hosts: all
  tasks:

    - name: record the output directory
      set_fact:
        output_file: "{{ remote_tmp_dir }}/foo.csv"
        output_file_csv: "{{ remote_tmp_dir }}/foo.csv"
        output_file_md: "{{ remote_tmp_dir }}/foo.md"
        non_existing_file: "{{ remote_tmp_dir }}/bar.csv"
        bad_location_file: "/bad/location/bad.csv"

    - name: include tasks
      block:

        - name: include tasks to perform basic tests
          include_tasks: tests/00-basic.yml

        - name: reset output file
          file:
            path: "{{ output_file }}"
            state: absent

        - name: include tasks to perform csv tests
          include_tasks: tests/01-csv-values.yml

        - name: reset output file
          file:
            path: "{{ output_file }}"
            state: absent

        - name: include tasks to perform markdown tests
          include_tasks: tests/02-md-values.yml

    - name: delete temporary directory
      file:
        path: "{{ remote_tmp_dir }}"
        state: absent
      no_log: yes
