---
ansible_python_interpreter: /usr/bin/env python

update_inventory_repo__repo_scheme: "ssh"
update_inventory_repo__repo_url: "ssh://git@gitea.admin.dettonville.int:2222/infra/report-inventory-facts.git"
update_inventory_repo__repo_branch: "master"
update_inventory_repo__file: "tests/inventory/site2.yml"
update_inventory_repo__git_ssh_private_keydir: "{{ __update_inventory_repo__git_ssh_private_keydir | d('~/.ssh' | expanduser) }}"
update_inventory_repo__git_ssh_private_keyfile: "ansible_repo.key"
update_inventory_repo__git_ssh_accept_hostkey: true

update_inventory_repo__host_list: []
#update_inventory_repo__host_list:
#  - hostname: vmlnx123-q1-s1.example.int
#    hostvars:
#      provisioning_data:
#        jira_id: DCC-12345
#        infra_group: MIDWA
#    groups:
#    - ntp_client
#    - ldap_client
#  - hostname: vmlnx124-q1-s1.example.int
#    hostvars:
#      provisioning_data:
#        jira_id: DCC-12346
#        infra_group: MIDWA
#    groups:
#    - ntp_client
#    - nfs_client
#    - ldap_client

