---

- name: "Include vars"
  include_vars: vars/vault.yml

- name: "Set facts"
  set_fact:
    __update_inventory_repo__git_ssh_private_key_path: "{{ update_inventory_repo__git_ssh_private_keydir }}/{{ update_inventory_repo__git_ssh_private_keyfile }}"

- name: "Display role params"
  debug:
    msg:
      update_inventory_repo__repo_scheme: "{{ update_inventory_repo__repo_scheme }}"
      update_inventory_repo__repo_url: "{{ update_inventory_repo__repo_url }}"
      update_inventory_repo__repo_branch: "{{ update_inventory_repo__repo_branch }}"
      update_inventory_repo__file: "{{ update_inventory_repo__file }}"
      __update_inventory_repo__git_ssh_private_key_path: "{{ __update_inventory_repo__git_ssh_private_key_path }}"

- name: "Set facts"
  set_fact:
    __update_inventory_repo__ssh_params:
      accept_hostkey: "{{ update_inventory_repo__git_ssh_accept_hostkey | d(True) }}"
      key_file: "{{ __update_inventory_repo__git_ssh_private_key_path }}"

- name: "Display __update_inventory_repo__ssh_params"
  debug:
    var: __update_inventory_repo__ssh_params

- name: "Ensure git private key is present at {{ __update_inventory_repo__git_ssh_private_key_path }}"
  copy:
    content: "{{ update_inventory_repo__git_ssh_private_key }}"
    dest: "{{ __update_inventory_repo__git_ssh_private_key_path }}"
    mode: "0600"
    backup: yes
#  no_log: yes

- name: "Add hosts to inventory file at {{ update_inventory_repo__file }}"
  dettonville.inventory.update_hosts:
    inventory_repo_scheme: "{{ update_inventory_repo__repo_scheme }}"
    inventory_repo_url: "{{ update_inventory_repo__repo_url }}"
    inventory_repo_branch: "{{ update_inventory_repo__repo_branch }}"
    inventory_file: "{{ update_inventory_repo__file }}"
    ssh_params: "{{ __update_inventory_repo__ssh_params }}"
    host_list: "{{ update_inventory_repo__host_list }}"
  register: update_hosts_to_repo_result

- name: "Display update_hosts_to_repo_result"
  debug:
    var: update_hosts_to_repo_result

